Task 2 commit
AleksejC/ToDoList pull request #1
Opened 2023-10-07 13:19 UTC by AleksejC

Completed task 2 for my dibil-teacher.

2023-10-07 13:34 UTC, AleksejC commented
![Снимок экрана (11)](https://github.com/AleksejC/ToDoList/assets/118013562/ec40ea48-e93f-45b4-88c0-da0decffcc57)
![Снимок экрана (12)](https://github.com/AleksejC/ToDoList/assets/118013562/aaa8cf40-1e3f-45a1-815d-eb431dc10bca)

2023-10-07 13:46 UTC, bartimeusss requested changes
And delete your comment - without it I won't approve

2023-10-07 13:46 UTC, bartimeusss commented on src/ToDoList.css
> +.newTaskBox {
```suggestion
.new-task-box {
```
Change it everywhere

2023-10-07 13:46 UTC, bartimeusss commented on src/ToDoList.tsx
> +    const [openWindow, setOpenWindow] = useState(false);
bool variables' names should start with `is`, `are`, `has`, `have` prefixes
`openWindow ` seems like function name

2023-10-07 13:46 UTC, bartimeusss commented on src/ToDoList.tsx
> +    }
```suggestion
    const addNewTaskButton = () => {
        setOpenWindow(!openWindow);
    }
```

2023-10-07 13:46 UTC, bartimeusss commented on src/ToDoList.tsx
> +    }
Also `addNewTaskButton ` seems like a bit weird name
Possible alternatives:

- just `onClick`
- `onAddNewTaskClick`
- `toggleAddNewTaskModal`

2023-10-07 13:46 UTC, bartimeusss commented on src/ToDoList.tsx
> +    }
Also you should use `useCallback` here

2023-10-07 13:46 UTC, bartimeusss commented on src/ToDoList.tsx
> +                            <p>New task name</p>
Tag `p` is not good choise here from semantic point of view
Use `label` instead

2023-10-07 13:46 UTC, bartimeusss commented on src/ToDoList.tsx
> +                            <p>Description</p>
Same

2023-10-07 13:46 UTC, bartimeusss commented on src/ToDoList.tsx
> +                                <button className='modalButtons'>Cancel</button>
I guess you should implement it in this PR as well

2023-10-07 23:49 UTC, bartimeusss approved these changes

2023-10-07 23:49 UTC, bartimeusss commented on src/ToDoList.css
> +    display: flex;
there is no display: flex required for children elements

2023-10-07 23:49 UTC, bartimeusss requested changes
Fix display: flex

2023-10-14 20:05 UTC, bartimeusss approved these changes

2023-10-14 20:05 UTC, merged