Task 3
AleksejC/ToDoList pull request #2
Opened 2023-10-14 19:53 UTC by AleksejC

Ability to save the task(after entering its name and description). Then it gets in "To do" column
![Снимок экрана (13)](https://github.com/AleksejC/ToDoList/assets/118013562/b970ef4e-a332-4c24-a81d-9a913b65d58e)
![Снимок экрана (14)](https://github.com/AleksejC/ToDoList/assets/118013562/c5606f1a-ae74-43c7-9aed-09965b1889d4)
![Снимок экрана (15)](https://github.com/AleksejC/ToDoList/assets/118013562/96da49ac-d23a-4848-8bf3-c815e434c5a9)

2023-10-14 20:30 UTC, bartimeusss requested changes

2023-10-14 20:30 UTC, bartimeusss commented on src/App.tsx
> +      <>
revert

2023-10-14 20:30 UTC, bartimeusss commented on src/Task/TaskCard.tsx
> +    return (
unnecessary return (arrow function could be inlined)

2023-10-14 20:30 UTC, bartimeusss commented on src/ToDoList/ToDoList.tsx
> +import React, {useCallback, useState} from 'react';
please configure 'Code style' section in WebStorm settings to have next style (add spaces inside curly braces):
```suggestion
import React, { useCallback, useState } from 'react';
```

2023-10-14 20:30 UTC, bartimeusss commented on src/Task/TaskCard.css
> +    height: 150px;
there is no need to specify `height` if `min-height` is specified

2023-10-14 20:30 UTC, bartimeusss commented on src/ToDoList/ToDoList.tsx
> +        clearAllInputs()
```suggestion
        clearAllInputs();
```

2023-10-14 20:30 UTC, bartimeusss commented on src/ToDoList/ToDoList.tsx
> +                            return <TaskCard task={it} />
1. You should provide `key` prop to each item when render components via `.map()`.
2. Unnecessary return in arrow function.

2023-10-14 20:30 UTC, bartimeusss commented on src/ToDoList/ToDoList.tsx
> +                                onChange={event => setCurrentTaskName(event.currentTarget.value)}
useCallback

2023-10-14 20:30 UTC, bartimeusss commented on src/ToDoList/ToDoList.tsx
> +                                onChange={event => setCurrentTaskDescription(event.currentTarget.value)}
useCallback

2023-10-14 20:31 UTC, bartimeusss requested changes
I can't see task `id`

2023-10-19 16:16 UTC, AleksejC commented on src/ToDoList/ToDoList.tsx
> +import React, {useCallback, useState} from 'react';
Which must be checked?
![Снимок экрана (16)](https://github.com/AleksejC/ToDoList/assets/118013562/a85a75e0-cb1e-46a7-96ef-bb8cb1f6b15c)

2023-10-19 21:18 UTC, bartimeusss requested changes

2023-10-19 21:18 UTC, bartimeusss commented on src/Task/TaskCard.tsx
> +            </div>
```suggestion
export const TaskCard: React.FC<TaskProps> = ({ task: { name, description, id} }) => (
    <div className='task-window'>
        <div className='task-id'>
            {id}
        </div>
        <div className='task-name'>
            {name}
        </div>
        <div className='task-description'>
            {description}
        </div>
    </div>
);
```

2023-10-19 21:18 UTC, bartimeusss commented on src/ToDoList/ToDoList.tsx
> +                        )}
```suggestion
                        {
                            toDoTasks.map(it => (
                                <TaskCard
                                    task={it}
                                    key={it.id}
                                />
                            )
                        }
```

2023-10-19 21:18 UTC, bartimeusss commented on src/ToDoList/ToDoList.tsx
> +    const id = parseFloat(Math.random().toFixed(4));
should be like this: "T-1", "T-2", etc.

2023-10-19 21:20 UTC, bartimeusss commented on src/ToDoList/ToDoList.tsx
> +import React, {useCallback, useState} from 'react';
<img width="986" alt="Screenshot 2023-10-19 at 23 20 01" src="https://github.com/AleksejC/ToDoList/assets/50061172/65ff0723-716e-41d2-bcbb-90bf2415a0cf">

2023-10-21 13:42 UTC, bartimeusss commented on src/Task/types.ts
> +    id: number | string;
```suggestion
    id: string;
```

2023-10-21 13:43 UTC, bartimeusss approved these changes

2023-10-21 13:44 UTC, merged